###
POST https://isdo.cmi.cz/Webservice/SOPData.asmx
Content-Type: application/soap+xml;charset=utf-8
action: "http://cmi.cz/getAllUsers"

<?xml version="1.0" encoding="utf-8"?>
<soap12:Envelope xmlns:soap12="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://cmi.cz/" xmlns="http://cmi.cz/"><soap12:Header><AuthHeader><AuthKey>c5edd6d0cde2fee0ecd7b4e66bb2ad9dcc78f34f</AuthKey></AuthHeader></soap12:Header><soap12:Body><getAllUsers/></soap12:Body></soap12:Envelope>

###
POST https://isdo.cmi.cz/Webservice/HeliosData.asmx
Content-Type: application/soap+xml;charset=utf-8
action: "http://cmi.cz/getAllEmployees"

<?xml version="1.0" encoding="utf-8"?>
<soap12:Envelope xmlns:soap12="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://cmi.cz/" xmlns="http://cmi.cz/"><soap12:Header><AuthHeader><AuthKey>bee907027e7e41d5fe2288571e4d64c8</AuthKey></AuthHeader></soap12:Header><soap12:Body><getAllEmployees/></soap12:Body></soap12:Envelope>

###
POST https://isdo.cmi.cz/Webservice/DataExport.asmx?WSDL
Content-Type: application/soap+xml;charset=utf-8
action: "http://cmi.cz/getZamestnanciList"

<?xml version="1.0" encoding="utf-8"?>
<soap12:Envelope xmlns:soap12="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://cmi.cz/" xmlns="http://cmi.cz/"><soap12:Header><AuthHeader><AuthKey>bee907027e7e41d5fe2288571e4d64c8</AuthKey></AuthHeader></soap12:Header><soap12:Body><getZamestnanciList/></soap12:Body></soap12:Envelope>

###
POST https://isdo.cmi.cz/Webservice/DataExport.asmx?WSDL
Content-Type: application/soap+xml;charset=utf-8
action: "http://cmi.cz/getRoleList"

<?xml version="1.0" encoding="utf-8"?>
<soap12:Envelope xmlns:soap12="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://cmi.cz/" xmlns="http://cmi.cz/"><soap12:Header><AuthHeader><AuthKey>bee907027e7e41d5fe2288571e4d64c8</AuthKey></AuthHeader></soap12:Header><soap12:Body><getRoleList/></soap12:Body></soap12:Envelope>

###
POST https://isdo.cmi.cz/Webservice/DataExport.asmx?WSDL
Content-Type: application/soap+xml;charset=utf-8
action: "http://cmi.cz/getKontakty"

<?xml version="1.0" encoding="utf-8"?>
<soap12:Envelope xmlns:soap12="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://cmi.cz/" xmlns="http://cmi.cz/"><soap12:Header><AuthHeader><AuthKey>bee907027e7e41d5fe2288571e4d64c8</AuthKey></AuthHeader></soap12:Header><soap12:Body><getKontakty/></soap12:Body></soap12:Envelope>

###
POST https://isdo.cmi.cz/Webservice/DataExport.asmx?WSDL
Content-Type: application/soap+xml;charset=utf-8
action: "http://cmi.cz/getSkupinyFunkci"

<?xml version="1.0" encoding="utf-8"?>
<soap12:Envelope xmlns:soap12="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://cmi.cz/" xmlns="http://cmi.cz/"><soap12:Header><AuthHeader><AuthKey>bee907027e7e41d5fe2288571e4d64c8</AuthKey></AuthHeader></soap12:Header><soap12:Body><getSkupinyFunkci/></soap12:Body></soap12:Envelope>

###
POST https://isdo.cmi.cz/Webservice/DataExport.asmx?WSDL
Content-Type: application/soap+xml;charset=utf-8
action: "http://cmi.cz/getFunkceVeSkupine"

<?xml version="1.0" encoding="utf-8"?>
<soap12:Envelope xmlns:soap12="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://cmi.cz/" xmlns="http://cmi.cz/"><soap12:Header><AuthHeader><AuthKey>bee907027e7e41d5fe2288571e4d64c8</AuthKey></AuthHeader></soap12:Header><soap12:Body><getFunkceVeSkupine><id_skupiny>2</id_skupiny></getFunkceVeSkupine></soap12:Body></soap12:Envelope>
