package works.iterative
package ui.model

import core.*

// Generic events that can be generated by forms
// When editing a form, you can
// - submit the form with some data (might be multiple options)
// - cancel the form editation
// - reset the form to its initial state
enum FormEvent[T]:
  case Submitted(data: T)
  case Cancelled extends FormEvent[Nothing]
  case Reset extends FormEvent[Nothing]

case class FormItem[Value](
    id: String,
    label: PlainOneLine,
    description: Option[PlainMultiLine],
    value: Value
)

case class FormSection(
    header: PlainOneLine,
    description: Option[PlainMultiLine],
    items: List[FormItem[_]]
)

case class Form(sections: List[FormSection])
