package ui.components.tailwind

trait TailwindSupport:
  // Make sure certain classes are included in the Tailwind JIT compiler
  // The sizes and colors that we generate dynamically are missed
  // So until I figure out how to use macros to mitigate, this should do
  val extraUserClasses: List[String] =
    List(
      "h-2",
      "h-3",
      "h-4",
      "h-5",
      "h-6",
      "h-8",
      "h-10",
      "h-12",
      "h-14",
      "h-16",
      "w-2",
      "w-3",
      "w-4",
      "w-5",
      "w-6",
      "w-8",
      "w-10",
      "w-12",
      "w-14",
      "w-16",
      "text-red-800",
      "text-amber-800",
      "text-green-800",
      "text-yellow-800",
      "bg-red-100",
      "bg-amber-100",
      "bg-green-100",
      "bg-yellow-100",
      "hover:bg-red-100",
      "hover:bg-amber-100",
      "hover:bg-green-100",
      "hover:bg-yellow-100",
      "hover:bg-red-200",
      "hover:bg-amber-200",
      "hover:bg-green-200",
      "hover:bg-yellow-200",
      "bg-green-50",
      "bg-amber-50",
      "bg-red-50",
      "bg-yellow-50",
      "bg-gray-600",
      "bg-red-600",
      "bg-orange-600",
      "bg-amber-600",
      "bg-yellow-600",
      "bg-lime-600",
      "bg-green-600",
      "bg-emerald-600",
      "bg-teal-600",
      "bg-cyan-600",
      "bg-sky-600",
      "bg-blue-600",
      "bg-indigo-600",
      "bg-violet-600",
      "bg-purple-600",
      "bg-fuchsia-600",
      "bg-pink-600",
      "bg-rose-600"
    )
